version: "3"

services:
  rufus:
    container_name: rufus
    hostname: rufus
    restart: unless-stopped
    image: rufus
    build:
      context: .
    environment:
      - DOCKER_MODE=Yes
      - GIT_PYTHON_REFRESH=quiet
      - BOT_TOKEN=$BOT_TOKEN
      - OSU_API_KEY=$OSU_API_KEY
      - OMDB_API_KEY=$OMDB_API_KEY
      - LASTFM_API_KEY=$LASTFM_API_KEY
      - WOLFRAM_API_KEY=$WOLFRAM_API_KEY
    volumes:
      - ./logs/bot.log:/app/logs/bot.log
    ports:
      - 8080:8080
